# Generated by Django 6.0.5 on 2026-05-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_confirmed_pickup',
            field=models.BooleanField(default=False, help_text="True once the buyer has confirmed the seller's proposed pickup time."),
        ),
    ]
