# Generated by Django 6.0.5 on 2026-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_businessprofile_company_size_businessprofile_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='WGS-84 latitude (-90 to 90)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='WGS-84 longitude (-180 to 180)', max_digits=10, null=True),
        ),
    ]
