# Generated by Django 6.0.5 on 2026-05-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_businessprofile_latitude_businessprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
