# Generated by Django 6.0.5 on 2026-05-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationtoken_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='notify_new_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_transaction_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='timezone',
            field=models.CharField(choices=[('Asia/Amman', 'Amman (GMT+3)'), ('Asia/Dubai', 'Dubai (GMT+4)'), ('Asia/Riyadh', 'Riyadh (GMT+3)'), ('Europe/London', 'London (GMT+0)'), ('America/New_York', 'New York (GMT-5)')], default='Asia/Amman', max_length=50),
        ),
    ]
